// Regenerates src/world.ts. Needs the data packages, which the extension does not ship:
//   npm i --no-save world-atlas topojson-client && node scripts/gen-world.mjs
// (run from this directory; writes world.ts to src/).
import { readFileSync, writeFileSync } from 'node:fs'
import { feature, mesh } from 'topojson-client'
const land = JSON.parse(readFileSync('node_modules/world-atlas/land-110m.json'))
const countries = JSON.parse(readFileSync('node_modules/world-atlas/countries-110m.json'))
const TOP = 84, BOTTOM = -58
const px = (lon) => +((lon + 180) * 2).toFixed(1)
const py = (lat) => +((TOP - lat) * 2).toFixed(1)
const ring = (pts) => pts.map(([lo, la], i) => `${i ? 'L' : 'M'}${px(lo)} ${py(Math.max(BOTTOM, Math.min(TOP, la)))}`).join('')
const landPath = feature(land, land.objects.land).features.flatMap((f) =>
  f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates).flatMap((poly) => poly.map((r) => ring(r) + 'Z')).join('')
const borders = mesh(countries, countries.objects.countries, (a, b) => a !== b)
const borderPath = borders.coordinates.map((l) => ring(l)).join('')
const out = `// Copyright ©️ 2026 km4be
// SPDX-License-Identifier: MIT
//
// GENERATED by scripts/gen-world.mjs from Natural Earth 110m (public domain)
// via world-atlas. Equirectangular, ${720}x${(TOP - BOTTOM) * 2} units:
// x = (lon + 180) * 2, y = (${TOP} - lat) * 2. Latitudes beyond ${TOP}/${BOTTOM} are clamped.

export const MAP_WIDTH = 720
export const MAP_HEIGHT = ${(TOP - BOTTOM) * 2}
export const MAP_TOP = ${TOP}

export const LAND_PATH = ${JSON.stringify(landPath)}
export const BORDER_PATH = ${JSON.stringify(borderPath)}
`
writeFileSync('src/world.ts', out)
console.log(out.length)
